### ISSUE TITLE
kml not uploading

### ISSUE THREAD

**Issue by petecutter** [Servir-Mekong/ecodash#8]
Not sure if this is due to a size issue / number of nodes o the polygon or what--or if there is a known node limit for GEE poly uploads. Could also be a header issue (I imported this into Google Earth from an ESRI shapefile and then saved as a kml).

I've attached the polygon i tried to use here for trouble shooting. Its a kmz but I've used the .zip suffix to be able to upload it here.

- Pete

**Comment by apoortinga** [comment]
I don't see the attached file. Can you upload the file again?

**Comment by apoortinga** [comment]
KML file was to large, which resulted in an ajax call with too many elements. Fixed issue by sampling coordinates.
